# Generated by Django 4.2.14 on 2024-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystockdata',
            name='price_change_1y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockdata',
            name='price_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockdata',
            name='price_change_30d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystockdata',
            name='top_gainer_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailystockdata',
            name='top_loser_24h',
            field=models.BooleanField(default=False),
        ),
    ]
