# Generated by Django 4.2.14 on 2024-07-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0002_dailystockdata_price_change_1y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockdata',
            name='close',
            field=models.FloatField(verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='high',
            field=models.FloatField(verbose_name='High Price'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='low',
            field=models.FloatField(verbose_name='Low Price'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='open',
            field=models.FloatField(verbose_name='Open Price'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='price_change_1y',
            field=models.FloatField(blank=True, null=True, verbose_name='Price Change (1y)'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='price_change_24h',
            field=models.FloatField(blank=True, null=True, verbose_name='Price Change (24h)'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='price_change_30d',
            field=models.FloatField(blank=True, null=True, verbose_name='Price Change (30d)'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='symbol',
            field=models.CharField(max_length=10, verbose_name='Stock Symbol'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='top_gainer_24h',
            field=models.BooleanField(default=False, verbose_name='Top Gainer (24h)'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='top_loser_24h',
            field=models.BooleanField(default=False, verbose_name='Top Loser (24h)'),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='volume',
            field=models.IntegerField(verbose_name='Volume'),
        ),
        migrations.AddIndex(
            model_name='dailystockdata',
            index=models.Index(fields=['symbol'], name='daily_stock_symbol_1133cc_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystockdata',
            index=models.Index(fields=['date'], name='daily_stock_date_207138_idx'),
        ),
    ]
