# Generated by Django 4.2.14 on 2024-08-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_alter_dailystockdata_close_alter_dailystockdata_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailystockdata',
            name='daily_stock_symbol_1133cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailystockdata',
            name='daily_stock_date_207138_idx',
        ),
        migrations.RemoveField(
            model_name='dailystockdata',
            name='price_change_1y',
        ),
        migrations.RemoveField(
            model_name='dailystockdata',
            name='price_change_24h',
        ),
        migrations.RemoveField(
            model_name='dailystockdata',
            name='price_change_30d',
        ),
        migrations.RemoveField(
            model_name='dailystockdata',
            name='top_gainer_24h',
        ),
        migrations.RemoveField(
            model_name='dailystockdata',
            name='top_loser_24h',
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dailystockdata',
            name='volume',
            field=models.BigIntegerField(),
        ),
        migrations.AlterModelTable(
            name='dailystockdata',
            table=None,
        ),
    ]
